name: Test bindings

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v2
    - name: Install package dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential git libboost-all-dev cmake libzmq3-dev libeigen3-dev
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-bindings-pip

    - name: Install Python dependencies (torch)
      run: python -m pip install --upgrade pip setuptools wheel torch torchvision

    - name: Get ProtoBuf code
      run: wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz && tar zxf protobuf-cpp-3.6.1.tar.gz
    - name: Compile ProtoBuf with old ABI (pre C++11)
      run: cd protobuf-3.6.1 && mkdir release && cd release && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/../../deps/ -D CMAKE_CXX_FLAGS="-fPIC -D_GLIBCXX_USE_CXX11_ABI=0" ../cmake/ && make && make install

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-ubuntu-bindings

    - name: Compile PS
      run: cmake -S . -B build_bindings -D PS_KEY_TYPE=int64_t -DPROTOBUF_PATH=$(pwd)/deps/lib/cmake/protobuf/ -D CMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" && cmake --build build_bindings --target adaps

    - name: Compile Bindings
      run: cd bindings && python setup.py install --user

    - name: Test torch and AdaPS import
      run: python3 bindings/test_import.py

    - name: Run example
      run: python3 bindings/example.py
