name: Test bindings

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Install package dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential git libboost-all-dev
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-bindings-pip

    - name: Install Python dependencies (torch)
      run: python -m pip install --upgrade pip setuptools wheel torch torchvision

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-ubuntu-bindings

    - name: Compile PS
      run: make ps KEY_TYPE=int64_t CXX11_ABI=$(python bindings/lookup_torch_abi.py) DEPS_PATH=$(pwd)/deps_bindings

    - name: Compile Bindings
      run: cd bindings && python setup.py install --user

    - name: Test torch and lapse import
      run: python3 bindings/test_import.py

    - name: Run example
      run: python3 bindings/example.py
