name: Run on latest Ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Install package dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential git libboost-all-dev
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-latest-ubuntu-v2

    - name: Compile
      run: make

    - name: Tests (quick)
      run: tests/run_tests.sh dont_compile

    - name: Apps
      run: tests/run_apps.sh

    - name: Compile with key tracing
      run: rm -rf build && export PS_LDFLAGS="-DPS_TRACE_KEYS=1" && make
